// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/goapi2/client/cve"
	"github.com/tttfrfr2/goapi2/client/health"
	"github.com/tttfrfr2/goapi2/client/lockfile"
	"github.com/tttfrfr2/goapi2/client/pkg_cpe"
	"github.com/tttfrfr2/goapi2/client/role"
	serverops "github.com/tttfrfr2/goapi2/client/server"
	"github.com/tttfrfr2/goapi2/client/task"
)

// Default goapi HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "rest.vuls.biz"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new goapi HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Goapi {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new goapi HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Goapi {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new goapi client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Goapi {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Goapi)
	cli.Transport = transport
	cli.Cve = cve.New(transport, formats)
	cli.Health = health.New(transport, formats)
	cli.Lockfile = lockfile.New(transport, formats)
	cli.PkgCpe = pkg_cpe.New(transport, formats)
	cli.Role = role.New(transport, formats)
	cli.Server = serverops.New(transport, formats)
	cli.Task = task.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Goapi is a client for goapi
type Goapi struct {
	Cve cve.ClientService

	Health health.ClientService

	Lockfile lockfile.ClientService

	PkgCpe pkg_cpe.ClientService

	Role role.ClientService

	Server serverops.ClientService

	Task task.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Goapi) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Cve.SetTransport(transport)
	c.Health.SetTransport(transport)
	c.Lockfile.SetTransport(transport)
	c.PkgCpe.SetTransport(transport)
	c.Role.SetTransport(transport)
	c.Server.SetTransport(transport)
	c.Task.SetTransport(transport)
}
