// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// ServerUpdateServerReader is a Reader for the ServerUpdateServer structure.
type ServerUpdateServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerUpdateServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerUpdateServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewServerUpdateServerOK creates a ServerUpdateServerOK with default headers values
func NewServerUpdateServerOK() *ServerUpdateServerOK {
	return &ServerUpdateServerOK{}
}

/* ServerUpdateServerOK describes a response with status code 200, with default header values.

OK response.
*/
type ServerUpdateServerOK struct {
	Payload *models.ServerUpdateServerResponseBody
}

func (o *ServerUpdateServerOK) Error() string {
	return fmt.Sprintf("[PUT /v1/server/{serverID}][%d] serverUpdateServerOK  %+v", 200, o.Payload)
}
func (o *ServerUpdateServerOK) GetPayload() *models.ServerUpdateServerResponseBody {
	return o.Payload
}

func (o *ServerUpdateServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerUpdateServerResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
