// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewServerGetServerDetailParams creates a new ServerGetServerDetailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServerGetServerDetailParams() *ServerGetServerDetailParams {
	return &ServerGetServerDetailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServerGetServerDetailParamsWithTimeout creates a new ServerGetServerDetailParams object
// with the ability to set a timeout on a request.
func NewServerGetServerDetailParamsWithTimeout(timeout time.Duration) *ServerGetServerDetailParams {
	return &ServerGetServerDetailParams{
		timeout: timeout,
	}
}

// NewServerGetServerDetailParamsWithContext creates a new ServerGetServerDetailParams object
// with the ability to set a context for a request.
func NewServerGetServerDetailParamsWithContext(ctx context.Context) *ServerGetServerDetailParams {
	return &ServerGetServerDetailParams{
		Context: ctx,
	}
}

// NewServerGetServerDetailParamsWithHTTPClient creates a new ServerGetServerDetailParams object
// with the ability to set a custom HTTPClient for a request.
func NewServerGetServerDetailParamsWithHTTPClient(client *http.Client) *ServerGetServerDetailParams {
	return &ServerGetServerDetailParams{
		HTTPClient: client,
	}
}

/* ServerGetServerDetailParams contains all the parameters to send to the API endpoint
   for the server get server detail operation.

   Typically these are written to a http.Request.
*/
type ServerGetServerDetailParams struct {

	/* Authorization.

	   api key auth
	*/
	Authorization *string

	/* ServerID.

	   Server ID

	   Format: int64
	*/
	ServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the server get server detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerGetServerDetailParams) WithDefaults() *ServerGetServerDetailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the server get server detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerGetServerDetailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the server get server detail params
func (o *ServerGetServerDetailParams) WithTimeout(timeout time.Duration) *ServerGetServerDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server get server detail params
func (o *ServerGetServerDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server get server detail params
func (o *ServerGetServerDetailParams) WithContext(ctx context.Context) *ServerGetServerDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server get server detail params
func (o *ServerGetServerDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server get server detail params
func (o *ServerGetServerDetailParams) WithHTTPClient(client *http.Client) *ServerGetServerDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server get server detail params
func (o *ServerGetServerDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the server get server detail params
func (o *ServerGetServerDetailParams) WithAuthorization(authorization *string) *ServerGetServerDetailParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the server get server detail params
func (o *ServerGetServerDetailParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithServerID adds the serverID to the server get server detail params
func (o *ServerGetServerDetailParams) WithServerID(serverID int64) *ServerGetServerDetailParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the server get server detail params
func (o *ServerGetServerDetailParams) SetServerID(serverID int64) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *ServerGetServerDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param serverID
	if err := r.SetPathParam("serverID", swag.FormatInt64(o.ServerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
