// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// ServerGetServerDetailReader is a Reader for the ServerGetServerDetail structure.
type ServerGetServerDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerGetServerDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerGetServerDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewServerGetServerDetailOK creates a ServerGetServerDetailOK with default headers values
func NewServerGetServerDetailOK() *ServerGetServerDetailOK {
	return &ServerGetServerDetailOK{}
}

/* ServerGetServerDetailOK describes a response with status code 200, with default header values.

OK response.
*/
type ServerGetServerDetailOK struct {
	Payload *models.ServerGetServerDetailResponseBody
}

func (o *ServerGetServerDetailOK) Error() string {
	return fmt.Sprintf("[GET /v1/server/{serverID}][%d] serverGetServerDetailOK  %+v", 200, o.Payload)
}
func (o *ServerGetServerDetailOK) GetPayload() *models.ServerGetServerDetailResponseBody {
	return o.Payload
}

func (o *ServerGetServerDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerGetServerDetailResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
