// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// RoleGetRoleDetailReader is a Reader for the RoleGetRoleDetail structure.
type RoleGetRoleDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoleGetRoleDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoleGetRoleDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRoleGetRoleDetailOK creates a RoleGetRoleDetailOK with default headers values
func NewRoleGetRoleDetailOK() *RoleGetRoleDetailOK {
	return &RoleGetRoleDetailOK{}
}

/* RoleGetRoleDetailOK describes a response with status code 200, with default header values.

OK response.
*/
type RoleGetRoleDetailOK struct {
	Payload *models.RoleGetRoleDetailResponseBody
}

func (o *RoleGetRoleDetailOK) Error() string {
	return fmt.Sprintf("[GET /v1/role/{roleID}][%d] roleGetRoleDetailOK  %+v", 200, o.Payload)
}
func (o *RoleGetRoleDetailOK) GetPayload() *models.RoleGetRoleDetailResponseBody {
	return o.Payload
}

func (o *RoleGetRoleDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleGetRoleDetailResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
