// Code generated by go-swagger; DO NOT EDIT.

package lockfile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/goapi2/models"
)

// LockfileGetLockfileListReader is a Reader for the LockfileGetLockfileList structure.
type LockfileGetLockfileListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LockfileGetLockfileListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLockfileGetLockfileListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLockfileGetLockfileListOK creates a LockfileGetLockfileListOK with default headers values
func NewLockfileGetLockfileListOK() *LockfileGetLockfileListOK {
	return &LockfileGetLockfileListOK{}
}

/* LockfileGetLockfileListOK describes a response with status code 200, with default header values.

OK response.
*/
type LockfileGetLockfileListOK struct {
	Payload *models.LockfileGetLockfileListResponseBody
}

func (o *LockfileGetLockfileListOK) Error() string {
	return fmt.Sprintf("[GET /v1/lockfiles][%d] lockfileGetLockfileListOK  %+v", 200, o.Payload)
}
func (o *LockfileGetLockfileListOK) GetPayload() *models.LockfileGetLockfileListResponseBody {
	return o.Payload
}

func (o *LockfileGetLockfileListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LockfileGetLockfileListResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
