// Code generated by go-swagger; DO NOT EDIT.

package lockfile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/goapi2/models"
)

// NewLockfileAddLockfileParams creates a new LockfileAddLockfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLockfileAddLockfileParams() *LockfileAddLockfileParams {
	return &LockfileAddLockfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLockfileAddLockfileParamsWithTimeout creates a new LockfileAddLockfileParams object
// with the ability to set a timeout on a request.
func NewLockfileAddLockfileParamsWithTimeout(timeout time.Duration) *LockfileAddLockfileParams {
	return &LockfileAddLockfileParams{
		timeout: timeout,
	}
}

// NewLockfileAddLockfileParamsWithContext creates a new LockfileAddLockfileParams object
// with the ability to set a context for a request.
func NewLockfileAddLockfileParamsWithContext(ctx context.Context) *LockfileAddLockfileParams {
	return &LockfileAddLockfileParams{
		Context: ctx,
	}
}

// NewLockfileAddLockfileParamsWithHTTPClient creates a new LockfileAddLockfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewLockfileAddLockfileParamsWithHTTPClient(client *http.Client) *LockfileAddLockfileParams {
	return &LockfileAddLockfileParams{
		HTTPClient: client,
	}
}

/* LockfileAddLockfileParams contains all the parameters to send to the API endpoint
   for the lockfile add lockfile operation.

   Typically these are written to a http.Request.
*/
type LockfileAddLockfileParams struct {

	// AddLockfileRequestBody.
	AddLockfileRequestBody *models.LockfileAddLockfileRequestBody

	/* Authorization.

	   api key auth
	*/
	Authorization *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lockfile add lockfile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LockfileAddLockfileParams) WithDefaults() *LockfileAddLockfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lockfile add lockfile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LockfileAddLockfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) WithTimeout(timeout time.Duration) *LockfileAddLockfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) WithContext(ctx context.Context) *LockfileAddLockfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) WithHTTPClient(client *http.Client) *LockfileAddLockfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddLockfileRequestBody adds the addLockfileRequestBody to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) WithAddLockfileRequestBody(addLockfileRequestBody *models.LockfileAddLockfileRequestBody) *LockfileAddLockfileParams {
	o.SetAddLockfileRequestBody(addLockfileRequestBody)
	return o
}

// SetAddLockfileRequestBody adds the addLockfileRequestBody to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) SetAddLockfileRequestBody(addLockfileRequestBody *models.LockfileAddLockfileRequestBody) {
	o.AddLockfileRequestBody = addLockfileRequestBody
}

// WithAuthorization adds the authorization to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) WithAuthorization(authorization *string) *LockfileAddLockfileParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the lockfile add lockfile params
func (o *LockfileAddLockfileParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *LockfileAddLockfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AddLockfileRequestBody != nil {
		if err := r.SetBodyParam(o.AddLockfileRequestBody); err != nil {
			return err
		}
	}

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
