// Code generated by go-swagger; DO NOT EDIT.

package cve

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// CveGetCveDetailReader is a Reader for the CveGetCveDetail structure.
type CveGetCveDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CveGetCveDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCveGetCveDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCveGetCveDetailOK creates a CveGetCveDetailOK with default headers values
func NewCveGetCveDetailOK() *CveGetCveDetailOK {
	return &CveGetCveDetailOK{}
}

/* CveGetCveDetailOK describes a response with status code 200, with default header values.

OK response.
*/
type CveGetCveDetailOK struct {
	Payload *models.CveGetCveDetailResponseBody
}

func (o *CveGetCveDetailOK) Error() string {
	return fmt.Sprintf("[GET /v1/cve/{cveID}][%d] cveGetCveDetailOK  %+v", 200, o.Payload)
}
func (o *CveGetCveDetailOK) GetPayload() *models.CveGetCveDetailResponseBody {
	return o.Payload
}

func (o *CveGetCveDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CveGetCveDetailResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
