// Code generated by go-swagger; DO NOT EDIT.

package pkg_cpe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPkgCpeGetPkgCpeListParams creates a new PkgCpeGetPkgCpeListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPkgCpeGetPkgCpeListParams() *PkgCpeGetPkgCpeListParams {
	return &PkgCpeGetPkgCpeListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPkgCpeGetPkgCpeListParamsWithTimeout creates a new PkgCpeGetPkgCpeListParams object
// with the ability to set a timeout on a request.
func NewPkgCpeGetPkgCpeListParamsWithTimeout(timeout time.Duration) *PkgCpeGetPkgCpeListParams {
	return &PkgCpeGetPkgCpeListParams{
		timeout: timeout,
	}
}

// NewPkgCpeGetPkgCpeListParamsWithContext creates a new PkgCpeGetPkgCpeListParams object
// with the ability to set a context for a request.
func NewPkgCpeGetPkgCpeListParamsWithContext(ctx context.Context) *PkgCpeGetPkgCpeListParams {
	return &PkgCpeGetPkgCpeListParams{
		Context: ctx,
	}
}

// NewPkgCpeGetPkgCpeListParamsWithHTTPClient creates a new PkgCpeGetPkgCpeListParams object
// with the ability to set a custom HTTPClient for a request.
func NewPkgCpeGetPkgCpeListParamsWithHTTPClient(client *http.Client) *PkgCpeGetPkgCpeListParams {
	return &PkgCpeGetPkgCpeListParams{
		HTTPClient: client,
	}
}

/* PkgCpeGetPkgCpeListParams contains all the parameters to send to the API endpoint
   for the pkg cpe get pkg cpe list operation.

   Typically these are written to a http.Request.
*/
type PkgCpeGetPkgCpeListParams struct {

	/* Authorization.

	   api key auth
	*/
	Authorization *string

	/* FilterCveID.

	   CveID filter
	*/
	FilterCveID *string

	/* FilterRoleID.

	   ServerRoleID filter
	*/
	FilterRoleID *int64

	/* FilterServerID.

	   ServerID filter
	*/
	FilterServerID *int64

	/* FilterTaskID.

	   TaskID filter
	*/
	FilterTaskID *int64

	/* Limit.

	   Limit

	   Default: 20
	*/
	Limit *int64

	/* Offset.

	   Offset
	*/
	Offset *int64

	/* Page.

	   Page Number

	   Default: 1
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pkg cpe get pkg cpe list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PkgCpeGetPkgCpeListParams) WithDefaults() *PkgCpeGetPkgCpeListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pkg cpe get pkg cpe list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PkgCpeGetPkgCpeListParams) SetDefaults() {
	var (
		limitDefault = int64(20)

		offsetDefault = int64(0)

		pageDefault = int64(1)
	)

	val := PkgCpeGetPkgCpeListParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
		Page:   &pageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithTimeout(timeout time.Duration) *PkgCpeGetPkgCpeListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithContext(ctx context.Context) *PkgCpeGetPkgCpeListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithHTTPClient(client *http.Client) *PkgCpeGetPkgCpeListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithAuthorization(authorization *string) *PkgCpeGetPkgCpeListParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithFilterCveID adds the filterCveID to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithFilterCveID(filterCveID *string) *PkgCpeGetPkgCpeListParams {
	o.SetFilterCveID(filterCveID)
	return o
}

// SetFilterCveID adds the filterCveId to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetFilterCveID(filterCveID *string) {
	o.FilterCveID = filterCveID
}

// WithFilterRoleID adds the filterRoleID to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithFilterRoleID(filterRoleID *int64) *PkgCpeGetPkgCpeListParams {
	o.SetFilterRoleID(filterRoleID)
	return o
}

// SetFilterRoleID adds the filterRoleId to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetFilterRoleID(filterRoleID *int64) {
	o.FilterRoleID = filterRoleID
}

// WithFilterServerID adds the filterServerID to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithFilterServerID(filterServerID *int64) *PkgCpeGetPkgCpeListParams {
	o.SetFilterServerID(filterServerID)
	return o
}

// SetFilterServerID adds the filterServerId to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetFilterServerID(filterServerID *int64) {
	o.FilterServerID = filterServerID
}

// WithFilterTaskID adds the filterTaskID to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithFilterTaskID(filterTaskID *int64) *PkgCpeGetPkgCpeListParams {
	o.SetFilterTaskID(filterTaskID)
	return o
}

// SetFilterTaskID adds the filterTaskId to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetFilterTaskID(filterTaskID *int64) {
	o.FilterTaskID = filterTaskID
}

// WithLimit adds the limit to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithLimit(limit *int64) *PkgCpeGetPkgCpeListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithOffset(offset *int64) *PkgCpeGetPkgCpeListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithPage adds the page to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) WithPage(page *int64) *PkgCpeGetPkgCpeListParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the pkg cpe get pkg cpe list params
func (o *PkgCpeGetPkgCpeListParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *PkgCpeGetPkgCpeListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.FilterCveID != nil {

		// query param filterCveID
		var qrFilterCveID string

		if o.FilterCveID != nil {
			qrFilterCveID = *o.FilterCveID
		}
		qFilterCveID := qrFilterCveID
		if qFilterCveID != "" {

			if err := r.SetQueryParam("filterCveID", qFilterCveID); err != nil {
				return err
			}
		}
	}

	if o.FilterRoleID != nil {

		// query param filterRoleID
		var qrFilterRoleID int64

		if o.FilterRoleID != nil {
			qrFilterRoleID = *o.FilterRoleID
		}
		qFilterRoleID := swag.FormatInt64(qrFilterRoleID)
		if qFilterRoleID != "" {

			if err := r.SetQueryParam("filterRoleID", qFilterRoleID); err != nil {
				return err
			}
		}
	}

	if o.FilterServerID != nil {

		// query param filterServerID
		var qrFilterServerID int64

		if o.FilterServerID != nil {
			qrFilterServerID = *o.FilterServerID
		}
		qFilterServerID := swag.FormatInt64(qrFilterServerID)
		if qFilterServerID != "" {

			if err := r.SetQueryParam("filterServerID", qFilterServerID); err != nil {
				return err
			}
		}
	}

	if o.FilterTaskID != nil {

		// query param filterTaskID
		var qrFilterTaskID int64

		if o.FilterTaskID != nil {
			qrFilterTaskID = *o.FilterTaskID
		}
		qFilterTaskID := swag.FormatInt64(qrFilterTaskID)
		if qFilterTaskID != "" {

			if err := r.SetQueryParam("filterTaskID", qFilterTaskID); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
