// Code generated by go-swagger; DO NOT EDIT.

package pkg_cpe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// PkgCpeGetCpeDetailReader is a Reader for the PkgCpeGetCpeDetail structure.
type PkgCpeGetCpeDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PkgCpeGetCpeDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPkgCpeGetCpeDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPkgCpeGetCpeDetailOK creates a PkgCpeGetCpeDetailOK with default headers values
func NewPkgCpeGetCpeDetailOK() *PkgCpeGetCpeDetailOK {
	return &PkgCpeGetCpeDetailOK{}
}

/* PkgCpeGetCpeDetailOK describes a response with status code 200, with default header values.

OK response.
*/
type PkgCpeGetCpeDetailOK struct {
	Payload *models.PkgCpeGetCpeDetailResponseBody
}

func (o *PkgCpeGetCpeDetailOK) Error() string {
	return fmt.Sprintf("[GET /v1/pkgCpe/cpe/{cpeID}][%d] pkgCpeGetCpeDetailOK  %+v", 200, o.Payload)
}
func (o *PkgCpeGetCpeDetailOK) GetPayload() *models.PkgCpeGetCpeDetailResponseBody {
	return o.Payload
}

func (o *PkgCpeGetCpeDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PkgCpeGetCpeDetailResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
