// Code generated by go-swagger; DO NOT EDIT.

package pkg_cpe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPkgCpeDeleteCpeParams creates a new PkgCpeDeleteCpeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPkgCpeDeleteCpeParams() *PkgCpeDeleteCpeParams {
	return &PkgCpeDeleteCpeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPkgCpeDeleteCpeParamsWithTimeout creates a new PkgCpeDeleteCpeParams object
// with the ability to set a timeout on a request.
func NewPkgCpeDeleteCpeParamsWithTimeout(timeout time.Duration) *PkgCpeDeleteCpeParams {
	return &PkgCpeDeleteCpeParams{
		timeout: timeout,
	}
}

// NewPkgCpeDeleteCpeParamsWithContext creates a new PkgCpeDeleteCpeParams object
// with the ability to set a context for a request.
func NewPkgCpeDeleteCpeParamsWithContext(ctx context.Context) *PkgCpeDeleteCpeParams {
	return &PkgCpeDeleteCpeParams{
		Context: ctx,
	}
}

// NewPkgCpeDeleteCpeParamsWithHTTPClient creates a new PkgCpeDeleteCpeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPkgCpeDeleteCpeParamsWithHTTPClient(client *http.Client) *PkgCpeDeleteCpeParams {
	return &PkgCpeDeleteCpeParams{
		HTTPClient: client,
	}
}

/* PkgCpeDeleteCpeParams contains all the parameters to send to the API endpoint
   for the pkg cpe delete cpe operation.

   Typically these are written to a http.Request.
*/
type PkgCpeDeleteCpeParams struct {

	/* Authorization.

	   api key auth
	*/
	Authorization *string

	/* CpeID.

	   cpe ID

	   Format: int64
	*/
	CpeID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pkg cpe delete cpe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PkgCpeDeleteCpeParams) WithDefaults() *PkgCpeDeleteCpeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pkg cpe delete cpe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PkgCpeDeleteCpeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) WithTimeout(timeout time.Duration) *PkgCpeDeleteCpeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) WithContext(ctx context.Context) *PkgCpeDeleteCpeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) WithHTTPClient(client *http.Client) *PkgCpeDeleteCpeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) WithAuthorization(authorization *string) *PkgCpeDeleteCpeParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithCpeID adds the cpeID to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) WithCpeID(cpeID int64) *PkgCpeDeleteCpeParams {
	o.SetCpeID(cpeID)
	return o
}

// SetCpeID adds the cpeId to the pkg cpe delete cpe params
func (o *PkgCpeDeleteCpeParams) SetCpeID(cpeID int64) {
	o.CpeID = cpeID
}

// WriteToRequest writes these params to a swagger request
func (o *PkgCpeDeleteCpeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param cpeID
	if err := r.SetPathParam("cpeID", swag.FormatInt64(o.CpeID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
