// Code generated by go-swagger; DO NOT EDIT.

package pkg_cpe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// PkgCpeGetPkgDetailReader is a Reader for the PkgCpeGetPkgDetail structure.
type PkgCpeGetPkgDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PkgCpeGetPkgDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPkgCpeGetPkgDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPkgCpeGetPkgDetailOK creates a PkgCpeGetPkgDetailOK with default headers values
func NewPkgCpeGetPkgDetailOK() *PkgCpeGetPkgDetailOK {
	return &PkgCpeGetPkgDetailOK{}
}

/* PkgCpeGetPkgDetailOK describes a response with status code 200, with default header values.

OK response.
*/
type PkgCpeGetPkgDetailOK struct {
	Payload *models.PkgCpeGetPkgDetailResponseBody
}

func (o *PkgCpeGetPkgDetailOK) Error() string {
	return fmt.Sprintf("[GET /v1/pkgCpe/pkg/{pkgID}][%d] pkgCpeGetPkgDetailOK  %+v", 200, o.Payload)
}
func (o *PkgCpeGetPkgDetailOK) GetPayload() *models.PkgCpeGetPkgDetailResponseBody {
	return o.Payload
}

func (o *PkgCpeGetPkgDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PkgCpeGetPkgDetailResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
