// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tttfrfr2/tempfiles/openapi/gen/models"
)

// TaskUpdateTaskReader is a Reader for the TaskUpdateTask structure.
type TaskUpdateTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TaskUpdateTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTaskUpdateTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTaskUpdateTaskOK creates a TaskUpdateTaskOK with default headers values
func NewTaskUpdateTaskOK() *TaskUpdateTaskOK {
	return &TaskUpdateTaskOK{}
}

/* TaskUpdateTaskOK describes a response with status code 200, with default header values.

OK response.
*/
type TaskUpdateTaskOK struct {
	Payload *models.TaskUpdateTaskResponseBody
}

func (o *TaskUpdateTaskOK) Error() string {
	return fmt.Sprintf("[PUT /v1/task/{taskID}][%d] taskUpdateTaskOK  %+v", 200, o.Payload)
}
func (o *TaskUpdateTaskOK) GetPayload() *models.TaskUpdateTaskResponseBody {
	return o.Payload
}

func (o *TaskUpdateTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskUpdateTaskResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
