// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHealthHealthParams creates a new HealthHealthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHealthHealthParams() *HealthHealthParams {
	return &HealthHealthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHealthHealthParamsWithTimeout creates a new HealthHealthParams object
// with the ability to set a timeout on a request.
func NewHealthHealthParamsWithTimeout(timeout time.Duration) *HealthHealthParams {
	return &HealthHealthParams{
		timeout: timeout,
	}
}

// NewHealthHealthParamsWithContext creates a new HealthHealthParams object
// with the ability to set a context for a request.
func NewHealthHealthParamsWithContext(ctx context.Context) *HealthHealthParams {
	return &HealthHealthParams{
		Context: ctx,
	}
}

// NewHealthHealthParamsWithHTTPClient creates a new HealthHealthParams object
// with the ability to set a custom HTTPClient for a request.
func NewHealthHealthParamsWithHTTPClient(client *http.Client) *HealthHealthParams {
	return &HealthHealthParams{
		HTTPClient: client,
	}
}

/* HealthHealthParams contains all the parameters to send to the API endpoint
   for the health health operation.

   Typically these are written to a http.Request.
*/
type HealthHealthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the health health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthHealthParams) WithDefaults() *HealthHealthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the health health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthHealthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the health health params
func (o *HealthHealthParams) WithTimeout(timeout time.Duration) *HealthHealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the health health params
func (o *HealthHealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the health health params
func (o *HealthHealthParams) WithContext(ctx context.Context) *HealthHealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the health health params
func (o *HealthHealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the health health params
func (o *HealthHealthParams) WithHTTPClient(client *http.Client) *HealthHealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the health health params
func (o *HealthHealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HealthHealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
