// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdvisoryResponseBody AdvisoryResponseBody
//
// Advisory describes a advisory
// Example: {"advisoryID":"advisoryID","osFamily":"redhat"}
//
// swagger:model AdvisoryResponseBody
type AdvisoryResponseBody struct {

	// AdvisoryID of advisory
	// Example: advisoryID
	// Required: true
	AdvisoryID *string `json:"advisoryID"`

	// osFamily of advisory
	// Example: redhat
	// Required: true
	OsFamily *string `json:"osFamily"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *AdvisoryResponseBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// AdvisoryID of advisory
		// Example: advisoryID
		// Required: true
		AdvisoryID *string `json:"advisoryID"`

		// osFamily of advisory
		// Example: redhat
		// Required: true
		OsFamily *string `json:"osFamily"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.AdvisoryID = props.AdvisoryID
	m.OsFamily = props.OsFamily
	return nil
}

// Validate validates this advisory response body
func (m *AdvisoryResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdvisoryID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOsFamily(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdvisoryResponseBody) validateAdvisoryID(formats strfmt.Registry) error {

	if err := validate.Required("advisoryID", "body", m.AdvisoryID); err != nil {
		return err
	}

	return nil
}

func (m *AdvisoryResponseBody) validateOsFamily(formats strfmt.Registry) error {

	if err := validate.Required("osFamily", "body", m.OsFamily); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this advisory response body based on context it is used
func (m *AdvisoryResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdvisoryResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdvisoryResponseBody) UnmarshalBinary(b []byte) error {
	var res AdvisoryResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
