// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DetectionToolResponseBody DetectionToolResponseBody
// Example: {"name":"changelog","patchAppliedAt":"2018-07-14T08:13:28Z"}
//
// swagger:model DetectionToolResponseBody
type DetectionToolResponseBody struct {

	// Detection Tool Name
	// Example: changelog
	// Required: true
	Name *string `json:"name"`

	// PatchAppliedAt
	// Example: 2018-07-14T08:13:28Z
	// Format: date-time
	PatchAppliedAt strfmt.DateTime `json:"patchAppliedAt,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *DetectionToolResponseBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// Detection Tool Name
		// Example: changelog
		// Required: true
		Name *string `json:"name"`

		// PatchAppliedAt
		// Example: 2018-07-14T08:13:28Z
		// Format: date-time
		PatchAppliedAt strfmt.DateTime `json:"patchAppliedAt,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Name = props.Name
	m.PatchAppliedAt = props.PatchAppliedAt
	return nil
}

// Validate validates this detection tool response body
func (m *DetectionToolResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePatchAppliedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DetectionToolResponseBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *DetectionToolResponseBody) validatePatchAppliedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.PatchAppliedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("patchAppliedAt", "body", "date-time", m.PatchAppliedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this detection tool response body based on context it is used
func (m *DetectionToolResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DetectionToolResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DetectionToolResponseBody) UnmarshalBinary(b []byte) error {
	var res DetectionToolResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
