// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LockfileUpdateLockfileRequestBody LockfileUpdateLockfileRequestBody
// Example: {"fileContent":"","path":"/FutureVuls/package.json"}
//
// swagger:model LockfileUpdateLockfileRequestBody
type LockfileUpdateLockfileRequestBody struct {

	// fileContent of the lockfile
	FileContent string `json:"fileContent,omitempty"`

	// Path of lockfile
	// Example: /FutureVuls/package.json
	Path string `json:"path,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *LockfileUpdateLockfileRequestBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// fileContent of the lockfile
		FileContent string `json:"fileContent,omitempty"`

		// Path of lockfile
		// Example: /FutureVuls/package.json
		Path string `json:"path,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.FileContent = props.FileContent
	m.Path = props.Path
	return nil
}

// Validate validates this lockfile update lockfile request body
func (m *LockfileUpdateLockfileRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this lockfile update lockfile request body based on context it is used
func (m *LockfileUpdateLockfileRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LockfileUpdateLockfileRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LockfileUpdateLockfileRequestBody) UnmarshalBinary(b []byte) error {
	var res LockfileUpdateLockfileRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
