// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PkgCpeDeleteCpeDeprecatedRequestBody PkgCpeDeleteCpeDeprecatedRequestBody
// Example: {"cpeID":5690894752894253000}
//
// swagger:model PkgCpeDeleteCpeDeprecatedRequestBody
type PkgCpeDeleteCpeDeprecatedRequestBody struct {

	// cpe ID
	// Example: 4046142736569201700
	// Required: true
	CpeID *int64 `json:"cpeID"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *PkgCpeDeleteCpeDeprecatedRequestBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// cpe ID
		// Example: 4046142736569201700
		// Required: true
		CpeID *int64 `json:"cpeID"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.CpeID = props.CpeID
	return nil
}

// Validate validates this pkg cpe delete cpe deprecated request body
func (m *PkgCpeDeleteCpeDeprecatedRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCpeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PkgCpeDeleteCpeDeprecatedRequestBody) validateCpeID(formats strfmt.Registry) error {

	if err := validate.Required("cpeID", "body", m.CpeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pkg cpe delete cpe deprecated request body based on context it is used
func (m *PkgCpeDeleteCpeDeprecatedRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PkgCpeDeleteCpeDeprecatedRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PkgCpeDeleteCpeDeprecatedRequestBody) UnmarshalBinary(b []byte) error {
	var res PkgCpeDeleteCpeDeprecatedRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
