// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RoleGetRoleListResponseBody RoleGetRoleListResponseBody
// Example: {"paging":{"limit":20,"offset":10,"page":1,"totalCount":200,"totalPage":10},"roles":[{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"},{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"}]}
//
// swagger:model RoleGetRoleListResponseBody
type RoleGetRoleListResponseBody struct {

	// paging
	Paging *PagingResponseBody `json:"paging,omitempty"`

	// ServerRole list
	// Example: [{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"},{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"},{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"}]
	Roles []*RoleListResponseBody `json:"roles"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *RoleGetRoleListResponseBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// paging
		Paging *PagingResponseBody `json:"paging,omitempty"`

		// ServerRole list
		// Example: [{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"},{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"},{"allTaskCount":10,"createdAt":"2018-07-14T08:13:28Z","id":1,"isDefault":true,"name":"server-role-name","newTaskCount":10,"secMetric":{"ar":"","cr":"","createdAt":"2018-07-14T08:13:28Z","ir":"","roleID":1,"roleName":"roleName","updatedAt":"2018-07-14T08:13:28Z"},"serverCount":10,"updatedAt":"2018-07-14T08:13:28Z"}]
		Roles []*RoleListResponseBody `json:"roles"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Paging = props.Paging
	m.Roles = props.Roles
	return nil
}

// Validate validates this role get role list response body
func (m *RoleGetRoleListResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoleGetRoleListResponseBody) validatePaging(formats strfmt.Registry) error {
	if swag.IsZero(m.Paging) { // not required
		return nil
	}

	if m.Paging != nil {
		if err := m.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paging")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paging")
			}
			return err
		}
	}

	return nil
}

func (m *RoleGetRoleListResponseBody) validateRoles(formats strfmt.Registry) error {
	if swag.IsZero(m.Roles) { // not required
		return nil
	}

	for i := 0; i < len(m.Roles); i++ {
		if swag.IsZero(m.Roles[i]) { // not required
			continue
		}

		if m.Roles[i] != nil {
			if err := m.Roles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("roles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this role get role list response body based on the context it is used
func (m *RoleGetRoleListResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePaging(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRoles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoleGetRoleListResponseBody) contextValidatePaging(ctx context.Context, formats strfmt.Registry) error {

	if m.Paging != nil {
		if err := m.Paging.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paging")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("paging")
			}
			return err
		}
	}

	return nil
}

func (m *RoleGetRoleListResponseBody) contextValidateRoles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Roles); i++ {

		if m.Roles[i] != nil {
			if err := m.Roles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("roles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RoleGetRoleListResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoleGetRoleListResponseBody) UnmarshalBinary(b []byte) error {
	var res RoleGetRoleListResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
