// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RoleUpdateRoleRequestBody RoleUpdateRoleRequestBody
// Example: {"roleName":"new-role-name"}
//
// swagger:model RoleUpdateRoleRequestBody
type RoleUpdateRoleRequestBody struct {

	// RoleName of role
	// Example: new-role-name
	RoleName string `json:"roleName,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *RoleUpdateRoleRequestBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// RoleName of role
		// Example: new-role-name
		RoleName string `json:"roleName,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.RoleName = props.RoleName
	return nil
}

// Validate validates this role update role request body
func (m *RoleUpdateRoleRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role update role request body based on context it is used
func (m *RoleUpdateRoleRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoleUpdateRoleRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoleUpdateRoleRequestBody) UnmarshalBinary(b []byte) error {
	var res RoleUpdateRoleRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
